// <auto-generated />
namespace JwtAuthentication.application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Jwt100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jwt100));
        
        string IMigrationMetadata.Id
        {
            get { return "201908171251122_Jwt1.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
